### ISSUE TITLE
RSS Feed not available anymore

### ISSUE THREAD

**Issue by svnlto** [PHPFrame/PHPFrame#10]
After we've made changes to the HTMLDocument previously, the RSS Feed Link is not being created anymore.

**Comment by lupomontero** [comment]
Thanks Sven.

I've been looking at this and the problem seems to be that in the E-NOISE theme 
we are replacing the doctype object in the HTMLDocument, and when this happens 
the DOM gets re-initialised using the new doctype, so all data stored in the 
DOM up until that point is lost. The RSS link in the head is being added by the 
CMS plugin before we render the theme, so thats why the link is disappearing 
from the final HTML output.

I have fixed this problem by [adding a method](http://github.com/lupomontero/PHPFrame/commit/de9919d6d4469ca79f9385a3e7dd6c30afb74c7e) called [addRSSLink()](http://www.phpframe.org/doc/api/Document/PHPFrame_HTMLDocument.html#methodaddRSSLink) to the HTMLDocument class, so now the plugin adds the RSS link by calling this method instead of directly manipulating the DOM. This allows the HTMLDocument object to cache the data in an internal variable and then use the data only when rendering itself as a string. This is the same technique used for meta tags, scripts and style sheets and it should work fine.

The latest build already includes this changes. You can download it from [here](http://dist.phpframe.org/PHPFrame-1.0.8-build.38.tgz).

Cheers,

Lupo
