### ISSUE TITLE
Crypt class genRandomPassword() limited max 40 chars.

### ISSUE THREAD

**Issue by songtao** [PHPFrame/PHPFrame#16]
The Crypt class genRandomPassword() will not create password bigger than 40 chars. Probably because hashing function.

**Comment by lupomontero** [comment]
Hi Songtao,

That is correct. PHPFrame_Crypt::genRandomPassword() creates a sha1 hash in order to create the random password. sha1 hashes are 40 characters long by definition, so that is the maximum length for the generated passwords. See link below to see the line of code responsible for this:

http://github.com/PHPFrame/PHPFrame/blob/master/src/PHPFrame/Utils/Crypt.php#L113

What do you need to generate longer passwords for? I guess we could modify this method to allow for longer passwords if needed. Let me know.

Best,

L

**Comment by lupomontero** [comment]
Closing this issue as we don't seem to need longer passwords, and longer passwords could be generated by concatenating the return of PHPFrame_Crypt::genRandomPassword() and then trimmed as necessary.
