### ISSUE TITLE
First normal request after xmlrpc request is ignored

### ISSUE THREAD

**Issue by chrismcband** [PHPFrame/PHPFrame#6]
If you make a normal http request, e.g. loading a file (index.php?controller=rooms&action=load_file&revisionid=5) the request appears to be completely ignored.
One thing that happens when you do the new normal request, is that the xmlrpc client in the session is woken up, the __wakeup() method receives no input and so request_dom is not initialised correctly with a fatal php error, I don't know if this would cause the request to be ignored completely.
This is a critical issue for us, it means that any normal requests (such as serving files through php) will not work. We are already experiencing this, we have a room which is initialised through xmlrpc, all images are loading except for the first one requested. Luis, please contact me as soon as you can, we have a deadline fast approaching.

**Comment by lupomontero** [comment]
Hi Chris,

I will look at this as a matter of urgency. I'll let you know as soon as a fix is available (within the next couple of days).

By the way, please check [Issue 3](http://github.com/PHPFrame/PHPFrame/issues#issue/3) for a resolution on the cookie_path issue.

Peace,

L

**Comment by lupomontero** [comment]
Chris,

This issue should have been fixed in my last commit. The changes passed the full test suite, including the new tests for reproducing Issues 1,3,5 and 6, and built as [http://dist.phpframe.org/PHPFrame-0.0.22-build.74.tgz](http://dist.phpframe.org/PHPFrame-0.0.22-build.74.tgz).

Note that it is now required to set the Content-Type header in the request to text/xml when sending XMLRPC requests. Otherwise they will not be recognised.

**Comment by chrismcband** [comment]
Great, can confirm this is working, all thumbnail images are loading correctly after the xmlrpc calls. Our xmlrpc calls already set the header to use content type text/xml so we didn't need to change anything.
