### ISSUE TITLE
XMLRPC, API design and application level error handling

### ISSUE THREAD

**Issue by lupomontero** [PHPFrame/PHPFrame#7]
In the last couple of weeks we have been refactoring the XMLRPC API as it
had not been looked at properly since the early days of 0.0.3 and most of the
handling of XMLRPC input and output is already in place, but other deeper and
more subtle issues now become more obvious. These are all related and in my
view they are the only design issues to be resolved in the current version of
the framework.

After implementing solutions for efficiently handling API requests (be it XML,
JSON or even simple HTTP GET commands) along with a consistent set of standards
for handling errors in controllers (by using $this->raiseError() and so on),
HTTP status codes and uncaught exceptions, we will have the first release
candidate, with the idea of releasing a stable version of the framework that we
will maintain both for E-NOISE (new site) and StickyWorld, as well as number of
other "beta" testers. We will need a stable version of the framework to install
on our live servers in the next few weeks, so expect a lot of activity and
contributions are welcome ;-)

Basically two points:
- Should we start writing API specific controllers or should we stick to
  writing controllers that are both used for web browsing and API interaction?
- We need to set out guidelines for error handling and adopt a standard for
  error (status) codes.

Up until now one of my goals had been to provide "transparent" I/O for
different kinds of _clients_. This means that now you can request any action on
any controller from any client and the app will deal with all the requests
without necessarily knowing anything about the client, the input and output
formats. This has its advantages, allowing us to write little code and relying
on the magic happening behind the curtains (in the framework).

However, after _living_ with this architecture for a while it now feels a bit
too rigid and ultimately utterly unrealistic. I find it very hard to think of a
real world app where you would need or even want to provide the exact same app
_interface_ (I don't mean the UI here) to browser users, other apps (XML or
JSON API) and the command line. I think it is essential that our apps support
all of them natively, but I also think we should change the approach in the
"userland" code (our controllers, models, helpers, plugins and views) with
regards to handling different clients. Each client type is used for a different
purpose and in my view each should have a different set of controllers and
actions. I would also enforce that each client is restricted to those methods
intended for them.

Pros in this approach:
- It reduces the complexity in testing and managing a huge number of possible
  supported requests.
- Makes it easier to design simpler and more specialised controllers
- Makes it a lot easier to design the overall APIs at a higher level, as you
  can only really look at _usability_ when you know _who_ is using the thing,
  _how_ and more importantly for _what_ purpose.
- Having discrete APIs makes it easier to scale apps as the app can be broken
  into interacting parts.
- Reinforces the tiered architecture of the MVC pattern. Controllers are the
  tip of the iceberg, simply there to interact with the "client" and leverage
  the logic and data shared in the models.
- Easier to document as it makes sense to have individual documentation for
  each client or API.
- Easier to use because of both better documentation and because it is easier
  to visualise each interface as a different gateway to the app, and not
  necessarily a single point of entry that tries to fit them all and struggles
  with the specific needs of each one.

What I mean is that we should probably be designing our apps with our real
_clients_ in mind and how we need to cater for their very specific needs. I
would like to see the new E-NOISE website handling its API calls separately
from the normal "page" requests, to make sure that each "interface" not only
supports a given standard, but where the app is actively conscious about the
different clients and has specific methods to deal each of them.

Instead of having an RPCObject or other work arounds we should simply have a
new controller action that gets the data the RPC call needs, then we
consciously pick what we want to return to the user and how.

Proposed implementation:
1. By default, apps should support all clients for all methods as it is now. I
   find this useful and it also guarantees backward compatibility.
2. We should write separate controllers or at least actions within the same
   controller to handle "expected" calls from RPC clients.
3. We should write a plugin to provide access enforcement and authentication
   methods to clients. The plugin architecture in the current framework version
   can easily support such a plugin and it would be a lot more flexible to have
   it as an addon and not part of the framework. It is a good idea to support
   different auth methods for different clients. I would like to see support 
   for public keys, key signature (currently used in 0.0.3), SSL and cookies.

With the proposed implementation we can keep working with what we have without
breaking anything, just adding a few API friendly controller actions and then
develop the plugin to fine tune each scenario and add advanced features.

I will write the basic outline for the plugin but it would be great if Chris,
with the help of Will and Songtao could implement it. That would give you a
good insight into the potential of plugins. This is a plugin that would be very
useful to all PHPFrame web apps.

In the meantime I could focus on the error handling thing as well as the CMS 
feature, another addon, that I think we will al find useful for our PHPFrame 
apps.

Thoughts?

**Comment by chrismcband** [comment]
I agree about the idea for dedicated controllers for different clients, having done it already in the old 0.0.3 branch we did have some actions that were being used both in the web site and as xmlrpc actions, but ran into a couple of minor unexpected issues that meant we weren't really saving anything by reusing the same code as we had to put in these small workarounds around different responses to send due to the client.
A dedicated controller would make the api for the client much clearer. It would make it easier to enforce, if we are using an acl, it would be much simpler just to enable all actions for one controller rather than having to manually specify each action for a subset of actions on a controller that an xmlrpc client can call.
However I can not see how a dedicated controller which picks and chooses what objects or data to send solves the issue of objects composed of many other objects.
I we are still using the RPCRenderer to directly render the data, this will only represent the objects (by default) by their array key/values based on using iterator_to_array. This only returns the object based on the private database fields needed for the object.

We would very much want to send a complete object in its entire structure, for instance, we have one action to get the room state used to initialise the StickyRoom when it first loads. We only need to load the room using our RoomMapper, which in turn will use other dedicated mappers to load all the sub-objects as necessary. The end result is a Room object which in turn contains all the members (containing Profiles), an array of work (each containing work note and an array of context notes belonging to the work), room note etc. We only have to send this one object by xmlrpc, on the client side, we have devised an elegant way to convert the xml rpc response (which we receive as a generic proxy object, just containing key/values) into the correct class instance. We just wrap the proxy object into an instance of the relevant class.

If the RPCRenderer is still going to be used and send the composite objects such as this, it needs to know about the internal structure of all the objects as it recurses through each field rendering the appropriate xml response elements. It makes sense that the objects themselves tell the RPCRenderer about the object structure to be sent.
I suppose you could do this another way specifying the object-field mapping in some sort of registry that the RPCRenderer could check.
Either way it needs to flexible enough to allow the RPCRenderer to send objects composed of other objects and allow the user should be choose what fields need to be sent, e.g. in one call to get the room details (name, description, welcome message) for a room, I might only want to send the room object without any work or members. We already have this implemented in the specialised mappers by setting some boolean flags.

We are planning to use the xmlrpc in a purely object-oriented fashion, just like an ordinary call locally on a function that returns an object, the only difference is this is remote and we have to go through a step of converting the object into the relevant class instance.

We'd be happy to do the plugin for authentication but we just need some guidance on it.

**Comment by lupomontero** [comment]
You are right, we need to extend the RPCRenderer to know how to "render" complex objects with nested references to other objects. It is the renderer's responsibility to represent data (be it integers, string, objects,...) in the right format, XML RPC in this case. This is something we may want to look at a lower level as well though.

Right now the PersistentObject class implements the IteratorAggregate interface allowing the objects to be treated as an associative array of a single dimension. This is useful for storing the object data into a db table but it doesn't allow iteration of the whole object structure including references to child objects and so on. 

We could:
- Add a new PersistentObject sub type implementing a Recursive Iterator interface, instead of the IteratorAggregate, that could be used for recursive structures.

and/or
- Create type specific methods in the renderers to handle objects with special rendering requirements.

Also glad to hear you guys are up for the API plugin ;-) I will set up a _subproject_ for the plugin with the file structure for developing, testing and publishing. Once this is set up (give me a couple of days) we could have a quick introductory session on skype or something. It'd probably take 1-2h.

L

**Comment by lupomontero** [comment]
Hi Chris,

With regards to the RPCObject issue I have been thinking about it and I think the simplest solution is to manually build the response data as an assoc array instead of directly passing the object to a view. Now that we are not using the same controller actions for handling API calls there is no need to use a view at all. I am using an action called "get" in our user controller to get user data via XMLRPC and it seems to work fine. The RPC renderer already knows how to render recursive arrays as XML structures so no extra coding is needed. Our User object contains a number of "Contact" objects and we are including them in the response. See the code for the action below for an example:

```
public function get($id)
{
    $id = filter_var($id, FILTER_VALIDATE_INT);
    if ($id === false) {
        $this->raiseError("Wrong user ID!");
        return;
    }

    $mapper = new UsersMapper($this->db());
    $user   = $mapper->findOne($id);

    if (!$user instanceof PHPFrame_User) {
        $this->raiseError("User not found!");
        return;
    }

    if (!$user->canRead($this->user())) {
        $this->raiseError("Permission denied!");
        return;
    }

    $struct = iterator_to_array($user);
    $struct["contacts"] = $user->contacts();

    $this->response()->body($struct);
}
```

L
